version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app 
    environment:
      - NODE_ENV=development
    depends_on:
      - waha

  waha:
    container_name: waha_new
    image: devlikeapro/waha:latest
    ports:
      - "3001:3000"
